// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4SoX5nFt_9JzYGIyAduBploHNfxOyCZE',
    appId: '1:69950032683:web:9a52b783702b9e34fdd36e',
    messagingSenderId: '69950032683',
    projectId: 'flutter-firebase-calendar',
    authDomain: 'flutter-firebase-calendar.firebaseapp.com',
    storageBucket: 'flutter-firebase-calendar.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQKleI_BEI_2DIuR8qb-Nsj0t6X75BOdg',
    appId: '1:69950032683:android:494342b308a4f2acfdd36e',
    messagingSenderId: '69950032683',
    projectId: 'flutter-firebase-calendar',
    storageBucket: 'flutter-firebase-calendar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1gA6uHFpreX_I4umn56UivdZMy41QWS4',
    appId: '1:69950032683:ios:83acc907e965b80ffdd36e',
    messagingSenderId: '69950032683',
    projectId: 'flutter-firebase-calendar',
    storageBucket: 'flutter-firebase-calendar.appspot.com',
    iosClientId: '69950032683-6brb42th2j49qja8s5nin2278pv3328m.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1gA6uHFpreX_I4umn56UivdZMy41QWS4',
    appId: '1:69950032683:ios:cbc8c4ac3750379ffdd36e',
    messagingSenderId: '69950032683',
    projectId: 'flutter-firebase-calendar',
    storageBucket: 'flutter-firebase-calendar.appspot.com',
    iosClientId: '69950032683-irtjv210fif9lbgdl6h7ng615un5ibe5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2.RunnerTests',
  );
}
